version: "3.8"

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: fuelphp-app
    ports:
      - "80:80"
    environment:
      - FUEL_ENV=development
    volumes:
      - ../:/var/www/html
    networks:
      - fuelphp-network

  db:
    build:
      context: ../
      dockerfile: docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: course_manager
    ports:
      - "3307:3306"
    networks:
      - fuelphp-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1 # 任意のサーバに接続可能にする
      - PMA_HOST=db      # dbサービスに接続する
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8080:80"        # ブラウザでは 8080番ポートを使う
    networks:
      - fuelphp-network

networks:
  fuelphp-network:
    driver: bridge
